// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAluguelVeiculos.Data;

#nullable disable

namespace SistemaAluguelVeiculos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702230649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SistemaAluguelVeiculos.Modelos.Cliente", b =>
                {
                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CPF");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaAluguelVeiculos.Modelos.ContratoAluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VeiculoPlaca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCPF");

                    b.HasIndex("VeiculoPlaca");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SistemaAluguelVeiculos.Modelos.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Placa");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator<string>("TipoVeiculo").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaAluguelVeiculos.Modelos.Carro", b =>
                {
                    b.HasBaseType("SistemaAluguelVeiculos.Modelos.Veiculo");

                    b.Property<int>("QuantidadePortas")
                        .HasColumnType("INTEGER");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("SistemaAluguelVeiculos.Modelos.Moto", b =>
                {
                    b.HasBaseType("SistemaAluguelVeiculos.Modelos.Veiculo");

                    b.Property<int>("Cilindradas")
                        .HasColumnType("INTEGER");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator().HasValue("Moto");
                });

            modelBuilder.Entity("SistemaAluguelVeiculos.Modelos.ContratoAluguel", b =>
                {
                    b.HasOne("SistemaAluguelVeiculos.Modelos.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAluguelVeiculos.Modelos.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoPlaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
